name: rscrapping code quality
on: [push]
jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.12"]

        steps:
            - uses: actions/checkout@v4

            - name: Set locale (required for inforemo parsing)
              run: |
                  sudo locale-gen es_ES.utf8 # Replace with your desired locale
                  sudo update-locale

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Pre-commit checks
              uses: pre-commit/action@v3.0.1

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pytest coverage
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

            - name: Test with pytest
              run: |
                  coverage run -m pytest

            - name: Coverage report
              run: |
                  coverage report -m
